definitions:
  tags: &common_tags
    - "remote"
    - "aks"
    - "{{ get-commit-hash.stdout }}"
  work_pool: &common_work_pool
    name: "kubernetes"
    job_variables:
      image: "{{ image }}"


deployments:
- name: "default"
  tags: *common_tags
  entrypoint: "flows/hello.py:hello_1"
  work_pool: *common_work_pool

- name: "arthur"
  tags: *common_tags
  entrypoint: "flows/hello.py:hello_1"
  parameters:
    name: "Arthur"
  work_pool: *common_work_pool

- name: "default"
  tags: *common_tags
  entrypoint: "flows/hello.py:hello_parallel_1"
  work_pool: *common_work_pool
